config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories
  resources :operations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  get 'reports', to: "reports#index"
  get 'reports_by_category', to: 'reports#report_by_category'
  get 'reports_by_dates', to: 'reports#report_by_dates'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  .text-center.text-danger
    / | The form contains #{pluralize(object.errors.count, "error")}.
  ul style="list-style: none;"
    - object.errors.full_messages.each do |msg|
      li
        .alert.alert-danger role="alert" = msg


app/views/shared/_flash_messages.html.slim
  - flash.each do |type, msg|
    - if type == "notice"
      .alert.alert-success.alert-dismissible.fade.show role="alert" data-controller="flash-messages" data-flash-messages-target="flash"
        = msg
        button.btn-close type="button" data-bs-dismiss="alert" aria-label="Close"
    - else
      .alert.alert-danger.alert-dismissible.fade.show role="alert"
        = msg
        button.btn-close type="button" data-bs-dismiss="alert" aria-label="Close"

app/views/shared/_footer.html.slim
footer.text-center.text-white
  .container.p-4.pb-0
    section
      .row
        .col.d-flex.flex-column.align-items-start.justify-content-around
          p.fw-bold.text-start
            | Sign up for our newsletter
          .form-outline.form-white.mb-4
            input.custom-input.text-field[type="email"]
          .social
            = link_to "https://www.facebook.com/nick0namesoon/", class: "btn text-white btn-floating m-1", style: "background-color: #3b5998"
              i.fab.fa-facebook-f
            = link_to "#", class: "btn text-white btn-floating m-1", style: "background-color: #dd4b39"
              i.fab.fa-google
            = link_to "#", class: "btn text-white btn-floating m-1", style: "background-color: #0082ca"
              i.fab.fa-linkedin-in
            = link_to "https://github.com/nicknamesoon", class: "btn text-white btn-floating m-1", style: "background-color: #333333"
              i.fab.fa-github

        .col.d-flex.justify-content-end
          = image_tag "logo.png", style: "max-width: 100%; height: 220px;"
  .text-center.p-3
    | © 2023 Copyright: by&nbsp;
    = link_to "#", style: "color: #00ffcb;"
      | Savchuk Volodymyr






/ .social
/   = link_to "https://www.facebook.com/profile.php?id=100017126328389", class: "btn text-white btn-floating m-1", style: "background-color: #3b5998"
/     i.fab.fa-facebook-f
/   = link_to "https://www.facebook.com/profile.php?id=100017126328389", class: "btn text-white btn-floating m-1", style: "background-color: #333333"
/     i.fab.fa-github

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-expand-custom.header.sticky-top
  .container-fluid
    = link_to root_path, class: "navbar-brand" do
      = image_tag "logo.png", alt: "logo", style: "width: 40px; height: auto; margin-right: 15px;"
      span
        | FINANCE MANAGER
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      i.fa-solid.fa-burger.m-auto style="color: #009879;"
    #navbarSupportedContent.collapse.navbar-collapse

      - if user_signed_in?
        = render "shared/private_navigation"
      - else
        = render "shared/public_navigation"


app/views/shared/_modal.html.slim
button.help-btn.position-fixed[type="button" data-bs-toggle="modal" data-bs-target="#exampleModal"]
    i.fa-solid.fa-circle-info
#exampleModal.modal.fade[tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"]
    .modal-dialog.modal-dialog-centered
      .modal-content
        .modal-header
          h1#exampleModalLabel.modal-title.fs-5
            | Допомога
          button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]
        .modal-body.d-flex.flex-column
          p style="color: #00ffcb;"
            |Aкаунт з тестовими данимим
          span.text-white
            | Email:&nbsp;testuser@mail.com
          span.text-white
            | Password:&nbsp;123456

app/views/shared/_pagination.html.slim
/ This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
/ calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").
/ The link variable is set to a proc that returns the link tag.
/ Usage: link.call( page_number [, text [, extra_attributes_string ]])
- link = pagy_link_proc(pagy)

nav.pagy_nav.pagination role="navigation"

  - if pagy.prev
    span.page.prev ==> link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"')
  - else
    span.page.prev.disabled ==> pagy_t('pagy.nav.prev')

  - pagy.series.each do |item|        # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
    - if item.is_a?(Integer)          # page link
      span.page ==> link.call(item)

    - elsif item.is_a?(String)        # current page
      span.page.current ==> item

    - elsif item == :gap              # page gap
      span.page.gap ==> pagy_t('pagy.nav.gap')

  - if pagy.next
    span.page.next == link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"')
  - else
    span.page.next.disabled == pagy_t('pagy.nav.next')

app/views/shared/_private_navigation.html.slim
ul.navbar-nav.ml-auto
  li.nav-item
    = link_to categories_path, class: "#{current_link_class(categories_path)} nav-link" do
      i.fa-solid.fa-clipboard-list
      | Категорії

  li.nav-item
    = link_to operations_path, class: "#{current_link_class(operations_path)} nav-link" do
      i.fa-regular.fa-credit-card
      | Операції

  li.nav-item
    = link_to reports_path, class: "#{current_link_class(reports_path)} nav-link" do
      i.fa-solid.fa-chart-pie
      | Звіти
  li.nav-item.dropdown
    a.nav-link.dropdown-toggle href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"
      i.fa-solid.fa-user-tie
      = current_user.email
    ul.dropdown-menu
      li
        = button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item"

app/views/shared/_public_navigation.html.slim
        ul.navbar-nav.me-auto.mb-2.mb-lg-0
          li.nav-item
            = link_to "Sign up", new_user_registration_path, class: "custom-btn success", role: "button"
          li.nav-item
            = link_to "Log in", new_user_session_path, class: "custom-btn secondary", role: "button"
