config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories
  resources :operations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  get 'reports', to: "reports#index"
  get 'reports_by_category', to: 'reports#report_by_category'
  get 'reports_by_dates', to: 'reports#report_by_dates'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :operations, dependent: :destroy

  validates :name, :description, presence: true
  validates :name,  uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @q = current_user.categories.ransack(params[:q])
    @q.sorts = 'name asc' if @q.sorts.empty?
    categories = @q.result(distinct: true)
    @pagy, @categories = pagy(categories)
  end

  def show
    add_breadcrumb "Всі категорії", categories_path
    add_breadcrumb "редагувати", edit_category_url(@category)
  end

  def new
    @category = current_user.categories.new
  end

  def edit
    add_breadcrumb "Всі категорії", categories_path
    add_breadcrumb "Перейти до категорії", category_url(@category)
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Категорія була успішно створена." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Категорія була успішно редагована." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Категорія була успішно видалена" }
    end
  end

  private

    def set_category
      @category = Category.find(params[:id]) rescue not_found
    end

    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.slim
h1.mb-4
  = category.name
  | &nbsp;(
  = category.description
  | )
.category
  - if category.operations.count <= 0
    h4.text-center
      | У вас немає транзакцій по даній категорії
  - else
    table.custom-table
      thead
        tr
          th #
          th Опис
          th Тип операції
          th Сума
          th Дата
      tbody
        - category.operations.each_with_index do |operation, i|
          tr
            td = i + 1
            td = link_to operation.description.truncate(100), operation
            td = type_to_word(operation.operation_type)
            td = operation.amount
            td = operation.operation_date.to_date

app/views/categories/_form.html.slim
= form_with(model: category) do |form|
  = render "shared/error_messages", object: category

  .row.g-3.align-items-center
    .col-2.text-end
       = form.label :name, class: "form-label fw-bold"
        | Назва категорії
    .col-3
       = form.text_field :name, class: "custom-input text-field"

  .row.g-3.align-items-center.my-3
    .col-2.text-end
       = form.label :description, class: "form-label fw-bold"
        | Короткий опис
    .col-6
       = form.text_field :description, class: "custom-input text-field"

  .row.mt-5
    .col-2.offset-2.d-flex
       button.custom-btn.success.me-4[type="submit"]
        | Зберегти
       button.button.custom-btn.secondary[type="reset"]
        | Очистити


app/views/categories/_search_form.html.slim
= search_form_for @q, class: "d-flex", data: { controller: "search-form", search_form_target: "form" } do |f|
  .col.d-flex
    = f.text_field :name_cont, class:"custom-input", placeholder: "Введіть перші літери назви категорії", data: { action: "keydown->search-form#search" }
    i.fa-sharp.fa-solid.fa-magnifying-glass.align-self-center.mx-2.fs-3 style="color: #00ffcb;"

app/views/categories/edit.html.slim
.container
  ol.breadcrumb.my-4
    = render_breadcrumbs :tag => :li, :separator => "&nbsp;/&nbsp;"

  h1.my-4
    | Редагування категорії
  .category
    = render "form", category: @category

app/views/categories/index.html.slim
.container.py-4
  h1.mb-4
    | Категорії витрат / доходів
  .category
    - if @categories.count <= 0
      p.text-center style="color: #7bf5a7;"
        | Ваш список категорій пустий
    - else
        .col-5.mb-2
          = render "search_form"

        table.custom-table
          thead
            tr
              th #
              th Назва
              th Опис
              th Управління
          tbody
            - @categories.each_with_index do |category, i|
              tr
                td = i + 1
                td = link_to category.name, category
                td = category.description
                td.d-flex.align-items-center
                  = link_to  edit_category_path(category), class: "link-btn icon-btn"
                      i.fa-solid.fa-pencil style="color: #00ffcb;"
                  = button_to category, class: "icon-btn", method: :delete
                      i.fa-solid.fa-trash style="color: #fc0303;"

  .col.d-flex.justify-content-between.align-items-center
    = link_to "Додати нову категорію", new_category_path, class: "custom-btn success", type: "button"
    == render partial: 'shared/pagination', locals: {pagy: @pagy}  if @categories.count > 0

app/views/categories/new.html.slim
.container.py-4
  h1.mb-4
    | Реєстрація нової категорії доходів / витрат
  .category
    = render "form", category: @category

app/views/categories/show.html.slim
.container.py-4
  ol.breadcrumb
    = render_breadcrumbs :tag => :li, :separator => "&nbsp;/&nbsp;"

  = render @category

  .col.d-flex
    = button_to "Видалити категорію", @category, method: :delete, class: "custom-btn danger me-4"
    = link_to "Додати нову транзакцію", new_operation_path, class: "custom-btn success" if @category.operations.count <= 0

