config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories
  resources :operations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  get 'reports', to: "reports#index"
  get 'reports_by_category', to: 'reports#report_by_category'
  get 'reports_by_dates', to: 'reports#report_by_dates'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/controllers/reports_controller.rb
require 'open_exchange_rates'
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_repot_options, only: %i[ report_by_category report_by_dates ]

  def index
    categories = current_user.categories
    @category_options = categories.map { |c| [c.name, c.id] }
  end

  def report_by_category
    @category_reports = current_user.operations
      .reports_by_category(params[:start_date], params[:last_date], params[:operation_type])
      .map do |key, value|
        [Category.find(key).name, convert(value, params[:currency])]
      end
  end

  def report_by_dates
    @date_reports = current_user.operations
      .reports_by_dates(params[:start_date],
                        params[:last_date],
                        params[:operation_type],
                        params[:operation][:category_id]
                      ).transform_values! do |value| convert(value, params[:currency]) end
  end

  private
  def convert(sum, from_currency = 'UAH', to_currency)
    fx = OpenExchangeRates::Rates.new
    fx.convert(sum, :from => from_currency, :to => to_currency)
  end

  def set_repot_options
    @report_options = { start_date: params[:start_date],
      last_date: params[:last_date],
      operation_type: params[:operation_type]
    }
  end
end

app/helpers/reports_helper.rb
module ReportsHelper

  def operation_sum(arr)
    arr.map {|el| el[1]}.sum
  end

  def exchange_rates(currency)
    case currency
    when 'UAH'
      'ua.jpeg'
    when 'USD'
      'usd.png'
    when 'EUR'
      'eur.jpeg'
    when 'PLN'
      'pln.png'
    when 'GBP'
      'gbr.png'
    end
  end
  def today_currency
    fx = OpenExchangeRates::Rates.new
    [
      {currency: fx.convert(1, from: 'PLN', to: 'UAH'), desc: 'Польського злотого', sign: 'zł'},
      {currency: fx.convert(1, from: 'USD', to: 'UAH'), desc: 'Американського доллара', sign: '$'},
      {currency: fx.convert(1, from: 'EUR', to: 'UAH'), desc: 'Євро', sign: '€'},
      {currency: fx.convert(1, from: 'GBP', to: 'UAH'), desc: 'Англійського фунта', sign: '£'}
    ]
  end
end

app/views/reports/_form.html.slim
= form_with(url: reports_by_category_path, method: :get, class: "main_report-form") do |form|
  .report_form
    .row.align-items-center.my-3
      .col-2.text-end
        = form.label :start_date, class: "form-label fw-bold"
          | Дата YYYY-MM-DD
      .col-3
        = form.date_field :start_date,  class: "custom-input text-field"

    .row.align-items-center.my-3
      .col-2.text-end
        = form.label :last_date, class: "form-label fw-bold"
          | Дата YYYY-MM-DD
      .col-3
        = form.date_field :last_date, class: "custom-input text-field"

    .row.align-items-center.my-3
      .col-2.text-end
        = label_tag :currency, "Валюта", class: "form-label fw-bold"
      .col-3
        = select_tag :currency, options_for_select(["UAH", "USD", "EUR", "PLN", "GBP"], selected: params[:currency]), class: "form-select custom-select"

    .row.align-items-center.my-3
      .col-2.text-end
        = label_tag :operation_type, class: "form-label fw-bold"
          | Тип операції
      .col-3
        select#operation_type.form-select.custom-select name="operation_type"
          - Operation.operation_types.keys.each do |t|
            option value="#{t}"
              = type_to_word(t)

    .row.align-items-center.my-3
      .col-2.text-end
        = label_tag :operation_type, class: "form-label fw-bold"
          | Категорія
      .col-3
        select#operation_category_id.form-select.custom-select name="operation[category_id]" data-action="focus->hide#hideBtn onfocusout->hide#showBtn"
          option desiabled="true"
            | Виберіть категорію
          - @category_options.each do |o|
            option value="#{o[1]}"
              = o[0]

    .row.align-items-center.my-5
      .col.offset-2

        button.custom-btn.success.me-4[type="submit" data-hide-target="button"]
          i.fa-solid.fa-chart-pie
          | Графік
        button.custom-btn.danger type="submit" formaction="#{reports_by_dates_path}"
          i.fa-solid.fa-chart-line
          | По датам

  .today_rates
    h1 Актуальні курси валют за сьогодні
    ul
      - today_currency.each do |item|
        li
          | Вартість гривні до &nbsp;
          = item[:desc]
          | &nbsp;
          = item[:currency]
          | &nbsp;
          = item[:sign]

app/views/reports/index.html.slim
.container.py-4
  h1 Генератор звітів

  .reports data-controller="hide"
    = render "form"

app/views/reports/report_by_category.html.slim
.container.my-4
  h2.fw-bold style="color: #00ffcb;"
    | Звіт за період: &nbsp;
    = @report_options[:start_date]
    | &nbsp;-&nbsp;
    = @report_options[:last_date]

  h3 style="color: #7bf5a7;"
    = type_to_word(@report_options[:operation_type])
    | &nbsp; в &nbsp;
    = params[:currency]
    | &nbsp;
    = image_tag(exchange_rates(params[:currency]), class: 'currency-flag', size: '40x30')

.container.py-4.border-top.mt-2
  .chart.row
    .col-3.p-4.category.mt-0
      table.custom-table style="max-width: 300px;"
        thead
          tr
            th Категорія
            th Сума
        tbody
          - @category_reports.each do |r|
            tr
              td.text-success = r[0]
              td = r[1]
          tr.table-success
            td colspan="2" style="color: white;"
              | Всього:&nbsp;
              = operation_sum(@category_reports)
              | &nbsp;
              = params[:currency]
    .col
      h2.text-center style="color: #00ffcb;"
        | Розподіл #{type_to_word(@report_options[:operation_type])} за період
      = pie_chart @category_reports, empty: "Заповніть будь ласка форму"

  h1 style="color:red;"
    / = @category_reports.to_a


app/views/reports/report_by_dates.html.slim
.container.mt-2.pt-4
  h2.text-center style="color: #00ffcb;"
    | Розподіл витрат за період по датам в
    | &nbsp;
    = params[:currency]
    | &nbsp;
    = image_tag(exchange_rates(params[:currency]), class: 'currency-flag', size: '40x30')
    | &nbsp;
    = @report_options[:start_date]
    | &nbsp;-&nbsp;
    = @report_options[:last_date]

  .col style="margin-top: 100px;"
    = line_chart @date_reports, label: "Сума",
                                xtitle: "Finance Manager",
                                ytitle: "Values", curve: false,
                                empty: "Заповніть будь ласка форму"
