config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories
  resources :operations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  get 'reports', to: "reports#index"
  get 'reports_by_category', to: 'reports#report_by_category'
  get 'reports_by_dates', to: 'reports#report_by_dates'

  match '*unmatched', to: 'application#not_found_method', via: :all
end

app/models/operation.rb
class Operation < ApplicationRecord

  belongs_to :category
  belongs_to :user

  validates :description, :operation_date, :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }

  enum operation_type: [:outlay, :income]

  scope :operations_by_category, ->(category_id) { where(category_id: category_id) }

  scope :reports_by_category, ->(start_date, last_date, operation_type) {
    where(operation_date: (start_date..last_date), operation_type: operation_type)
    .group(:category_id)
    .sum(:amount)
  }

  scope :reports_by_dates, ->(start_date, last_date, operation_type, category_id) {
    where(operation_date: (start_date..last_date), operation_type: operation_type, category_id: category_id)
    .group(:operation_date)
    .sum(:amount)
  }
  # private
  # def convert(sum, from_currency = 'UAH', to_currency)
  #   fx = OpenExchangeRates::Rates.new
  #   fx.convert(sum, :from => from_currency, :to => to_currency)
  # end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_operation, only: %i[ show edit update destroy ]
  before_action :set_category_options, only: %i[ new edit create ]

  def index
    @pagy, @operations = pagy(pagy_options)
    @categories = current_user.operations.includes([:category]).collect { |o| [o.category.name, o.category.id] }.uniq
    @category_exist = current_user.categories.count > 0 ? true : false
  end

  def show
    add_breadcrumb "Всі транзакції", operations_path
    add_breadcrumb "редагувати", edit_operation_url(@operation)
  end

  def new
    @operation = current_user.operations.new
  end

  def edit
    add_breadcrumb "Всі транзакції", operations_path
    add_breadcrumb "Перейти до транзакції", operation_url(@operation)
  end

  def create
    @operation = Operation.new(operation_params)
    @operation.user = current_user

    respond_to do |format|
      if @operation.save
        format.html { redirect_to operation_url(@operation), notice: "Операція була успішно створена." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: "Операція була успішно редагована." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Операція була успішно видалена." }
    end
  end

  private

    def pagy_options
      params[:operation] == nil ? current_user.operations : current_user.operations.operations_by_category(params[:operation][:category_id])
    end

    def set_operation
      @operation = Operation.find(params[:id]) rescue not_found
    end

    def set_category_options
      @category_options = current_user.categories.map { |c| [c.name, c.id]}
    end

    def operation_params
      params.require(:operation).permit(:name, :operation_type, :amount, :operation_date, :description, :category_id)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.slim
= form_with(model: operation) do |form|
  = render "shared/error_messages", object: operation

  .row.align-items-center
    .col-2.text-end
      label.form-label.fw-bold for="operation_category_id"
        | Назва категорії
    .col-3
      select#operation_category_id.form-select.custom-select name="operation[category_id]"
        - @category_options.each do |o|
          option value="#{o[1]}"
            = o[0]

  .row.align-items-center.my-3
    .col-2.text-end
      = form.label :operation_type, class: "form-label fw-bold"
        | Тип операції
    .col-3
      select#operation_type.form-select.custom-select name="operation[operation_type]"
        - Operation.operation_types.keys.each do |t|
          option value="#{t}"
            = type_to_word(t)

  .row.align-items-center.my-3
    .col-2.text-end
      = form.label :amount, class: "form-label fw-bold"
        | Сума
    .col-1
      = form.text_field :amount, class: "custom-input text-field"

  .row.align-items-center.my-3
    .col-2.text-end
      = form.label :description, class: "form-label fw-bold"
        | Короткий опис
    .col-6
      = form.text_field :description, class: "custom-input text-field"

  .row.align-items-center.my-3
    .col-2.text-end
      = form.label :operation_date, class: "form-label fw-bold"
        | Дата YYYY-MM-DD
    .col-3
      = form.date_field :operation_date, class: "custom-input text-field"

  .row.my-3
    .col-2.offset-2.d-flex
      button.custom-btn.success.me-4[type="submit"]
        | Зберегти
      button.custom-btn.secondary[type="reset"]
        | Очистити




app/views/operations/_operation.html.slim
h1.mb-4
  = operation.description

.category
  table.custom-table
      thead
        tr
          th Категорія
          th Опис
          th Тип операції
          th Сума
          th Дата
      tbody
        tr
          td = operation.category.name
          td = operation.description.truncate(100)
          td = type_to_word(operation.operation_type)
          td = operation.amount
          td = operation.operation_date.to_date

app/views/operations/_search_form.html.slim
= search_form_for @q, class: "d-flex" do |f|
  = f.select :category_id, class:"form-select"


app/views/operations/edit.html.slim
.container
  ol.breadcrumb.my-4
    = render_breadcrumbs :tag => :li, :separator => "&nbsp;/&nbsp;"

  h1.my-4
    | Редагування транзакції
  .category
    = render "form", operation: @operation

app/views/operations/index.html.slim
.container.py-4
  h1.mb-4
    | Транзакції

  .category
    - if @operations.count <= 0
      p.text-center style="color: #7bf5a7;"
        | Ваш список транзакцій пустий
    - else
      .col-3.mb-2
        = form_with(url: operations_path, method: :get, data: { controller: "search-form", search_form_target: "form" }) do |form|
          = form.select "operation[category_id]",  @categories, {include_blank: "Фільтр по категоріям"},  class: "form-select custom-select", onchange: 'this.form.submit();'

      table.custom-table
        thead
          tr
            th #
            th Категорія
            th Тип операції
            th Сума
            th Дата
            th Опис
            th Управління
        tbody
          - @operations.each_with_index do |operation, i|
            tr
              td = i + 1
              td = operation.category.name
              td = type_to_word(operation.operation_type)
              td = operation.amount
              td = operation.operation_date.to_date
              td = link_to operation.description.truncate(70), operation_path(operation)
              td.d-flex.align-items-center
                = link_to  edit_operation_path(operation), class: "link-btn icon-btn"
                    i.fa-solid.fa-pencil style="color: #00ffcb;"
                = button_to operation, class: "icon-btn", method: :delete
                    i.fa-solid.fa-trash style="color: #fc0303;"

  .col.d-flex.justify-content-between.align-items-center
    = link_to "#{@category_exist == false ? 'Додати нову категорію' : 'Додати нову транзакцію'}", "#{@category_exist == false ? new_category_path : new_operation_path}", class: "custom-btn success", type: "button"
    == render partial: 'shared/pagination', locals: {pagy: @pagy} if @operations.count > 0



app/views/operations/new.html.slim
.container.py-4
  h1.py-4
    | Реєстрація нової транзакції
  .category
    = render "form", operation: @operation

app/views/operations/show.html.slim
.container.py-4
  ol.breadcrumb
    = render_breadcrumbs :tag => :li, :separator => "&nbsp;/&nbsp;"

  = render @operation

  = button_to "Видалити транзакцію", @operation, method: :delete, class: "custom-btn danger"